apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-config
data:
  organization: "msazure"
  project: "CloudNativeCompute"
  masterValidationE2EID: "138746"
  aksBuildID: "74751"
  releaseID: "0"
  azureStorageAccount: "zuya20200921account"
  azureStorageContainer: "test"
