apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: zuya20200921acr.azurecr.io/monitor:v1
        args: [ "--config", "/config/config.json" ]
        volumeMounts:
          - mountPath: /config
            name: config-map
            readOnly: true
        env:
          - name: AZURE_STORAGE_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: accesskey
                name: monitor-secret
          - name: PERSONAL_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                key: pat
                name: monitor-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      volumes:
        - name: config-map
          configMap:
            name: monitor-config

