apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-config
data:
  config.json: |-
    {
      "organization": "msazure",
      "project": "CloudNativeCompute",
      "master_validation_e2e_id": 138746,
      "aks_build_id": 74751,
      "aks_release": [
        {
          "definition_id": 452,
          "source_alias": "ev2_artifacts",
          "staging": [
            "Prod: staging westus2"
          ]
        }
      ],
      "azure_storage_account": "{{ .Values.azureStorageAccount }}",
      "azure_storage_container": "{{ .Values.azureCICDContainer }}"
    }
