apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.registry }}/monitor:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --config=/config/config.json
        volumeMounts:
          - mountPath: /config
            name: config-map
            readOnly: true
        env:
          - name: AZURE_STORAGE_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: accesskey
                name: {{ .Values.secrets }}
          - name: PERSONAL_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                key: pat
                name: {{ .Values.secrets }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-map
          configMap:
            name: {{ .Values.configmap }}
      
