apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitor.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --config=/config/config.json
        volumeMounts:
          - mountPath: /config
            name: config-map
            readOnly: true
        env:
          - name: AZURE_STORAGE_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: accesskey
                name: monitor-secret
          - name: PERSONAL_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                key: pat
                name: monitor-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - name: config-map
          configMap:
            name: monitor-config
      
