apiVersion: v1
kind: Secret
metadata:
  name: monitor-secret
type: Opaque
data:
  accesskey: {{ .Values.storageAccountAccessKey | b64enc | quote }}
  pat: {{ .Values.personalAccessToken | b64enc | quote }}
