apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets }}
type: Opaque
data:
  accesskey: {{ .Values.env.storageAccountAccessKey | b64enc | quote }}
  pat: {{ .Values.env.personalAccessToken | b64enc | quote }}
