apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: zuya20200921acr.azurecr.io/monitor:v1
        env:
          - name: ORGANIZATION
            valueFrom:
              configMapKeyRef:
                key: organization
                name: monitor-config
          - name: PROJECT
            valueFrom:
              configMapKeyRef:
                key: project
                name: monitor-config
          - name: MASTER_VALIDATION_E2E_ID
            valueFrom:
              configMapKeyRef:
                key: masterValidationE2EID
                name: monitor-config
          - name: AKS_BUILD_ID
            valueFrom:
              configMapKeyRef:
                key: aksBuildID
                name: monitor-config
          - name: RELEASE_ID
            valueFrom:
              configMapKeyRef:
                key: releaseID
                name: monitor-config
          - name: AZURE_STORAGE_ACCOUNT
            valueFrom:
              configMapKeyRef:
                key: azureStorageAccount
                name: monitor-config
          - name: AZURE_STORAGE_CONTAINER
            valueFrom:
              configMapKeyRef:
                key: azureStorageContainer
                name: monitor-config
          - name: AZURE_STORAGE_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: accesskey
                name: monitor-secret
          - name: PERSONAL_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                key: pat
                name: monitor-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
